name: Branch Link Check

on:
  workflow_dispatch:
  schedule:
    - cron: "00 13 * * *" # run at 18:30 PM IST

jobs:
  paradox:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      with:
        ref: branch-0.1.x
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
      - uses: coursier/cache-action@v5

      - name: Paradox Validate Links
        working-directory: ./docs
        run: sbtn paradoxValidateLinks

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-linkcheck
