name: dev

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main, 'branch-*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"
          registry-url: "https://registry.npmjs.org"

      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
          apps: sbt sbtn

      - uses: coursier/cache-action@v6

      - name: Cache ~/.npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Docs makeSite
        working-directory: ./docs
        run: |
          sbt clean
          sbt makeSite

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ci

      - name: Generate RTM
        if: always()
        continue-on-error: true
        run: |
          sh rtm.sh

      - name: Upload RTM
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: RTM
          path: ./RTM

      - name: Upload Coverage
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: Coverage
          path: ./coverage

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
