name: dev

on:
  push:
    tags: 
      - "v*"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: increase file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"

      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
          apps: sbt sbtn

      - uses: coursier/cache-action@v5

      - name: Cache ~/.npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ci

      - name: Generate RTM
        if: always()
        continue-on-error: true
        run: |
          sh rtm.sh

      - name: Upload RTM
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: RTM
          path: ./RTM

      - name: Upload Coverage
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: ./coverage

      - name: Create rtm zip
        uses: thedoctor0/zip-release@master
        with:
          filename: 'RTM.zip'
          path: ./RTM

      - name: Create coverage zip
        uses: thedoctor0/zip-release@master
        with:
          filename: 'coverage.zip'
          path: ./coverage

      - name: Create build zip
        uses: thedoctor0/zip-release@master
        with:
          filename: 'esw-ocs-eng-ui.zip'
          path: ./esw-ocs-eng-ui

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./RTM.zip
            ./coverage.zip
            ./esw-ocs-eng-ui.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name:  Docs Publish
        working-directory: ./docs
        run: |
          echo 'echo $RELEASE_TOKEN' > /tmp/.git-askpass
          chmod +x /tmp/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt -Dprod.publish=true clean ghpagesPushSite
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_ASKPASS: /tmp/.git-askpass

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
